# Generated by Django 5.1.4 on 2024-12-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_receiptmodel_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptmodel',
            name='notes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='receiptmodel',
            name='purchaser',
            field=models.CharField(default='', max_length=250),
        ),
    ]
